Aligns births deaths pregnancy
starsimhub/starsim pull request #514
Opened 2024-05-17 21:58 UTC by kaa2102

### Description

### Checklist
- [ ] Code commented & docstrings added
- [ ] New tests were needed and have been added
- [ ] A new version number was needed & changelog has been updated
- [ ] A new PyPI version needs to be released

2024-05-20 21:23 UTC, kaa2102 commented
The PR changes the way Births are generated (from deterministic to stochastic and tied to Mothers to be CRN-safe). 2 tests fail in test_demographics.py --> test_nigeria() and test_constant_pop() due to the changes in the birth rate. Changing the death_rates and tolerances in the np.isclose() functions from 5% to 10-20%.

2024-05-21 00:05 UTC, RomeshA reviewed
I'm probably missing some of the context for the changes here and the specific issue being addressed - but curious how this will interact with the maternal network, which also tracks the relationships between mothers and unborn children? Is the plan to keep both of them, or to move tracking it directly in the `People` object?

2024-05-22 15:09 UTC, kaa2102 commented on starsim/people.py
> +            ss.Arr('parent_uids', dtype=[]), # List indicating the UID of mother giving birth
I had a chat with @cliffckerr on the approach and I am going to refactor the parent_uids `Arr` as an `IndexArr`  instead.

2024-05-22 15:11 UTC, kaa2102 commented on starsim/demographics.py
> +        np.array(mother_uids)
The `n_new` line is a piece of legacy code used to return the number of new uids (babies) to be added using `sim.people.grow(n_new)`.

2024-05-22 15:12 UTC, kaa2102 commented on starsim/demographics.py
> +            sim.people.parent_uids=[]
I am going to remove this code in the refactor from `Arr` to `IndexArr`.

2024-05-28 18:28 UTC, daniel-klein requested changes
Agree with the comments from @RomeshA and @cliffckerr that this PR needs to be refactored. As we discussed previously, we should not attempt to track every child a partner has, as that would be a one to many relationship, and instead only track a single parent for each newborn - a one to one relationship. This change should simplify the implementation and allow conformation with typical usage patterns of state array.

2024-05-29 15:10 UTC, closed without merging