Mixing pools ck
starsimhub/starsim pull request #727
Opened 2024-10-30 10:02 UTC by cliffckerr

Refactor of mixing pools branch prior to merging with `rc2.1.0`.

2024-10-30 16:11 UTC, daniel-klein commented on starsim/distributions.py
> +    integer = sc.sha(string, asint=True) # Hash the string to an integer
Consider updating the comment above to mention sc.sha

2024-10-30 16:12 UTC, daniel-klein commented on starsim/distributions.py
> +    integer = sc.sha(string, asint=True) # Hash the string to an integer
How did you choose 10M as the modulo?

2024-10-30 16:19 UTC, daniel-klein commented on starsim/networks.py
> +    A container for one or more MixingPool instances
Kinda, but not quite. It's not so much a "container" as it is a builder to create a rectangular matrix of MixingPool instances.

2024-10-30 16:22 UTC, daniel-klein commented on starsim/networks.py
> +            contact_matrix = np.array([[2.4, 0.49], [0.91, 0.16]]), # TODO: document where these came from
There is nothing to document here, the values are made up and intended to be replaced by the user - as are the `src` and `dst`. Is there a better way, perhaps taking `None` as the default and throwing an error if user input is not supplied?

2024-10-30 16:28 UTC, daniel-klein commented on starsim/networks.py
> +        return n_new_cases
Missing new line at end of file.

2024-10-30 16:41 UTC, daniel-klein reviewed
A few recommended change, including `rate_prob`

2024-10-30 16:42 UTC, daniel-klein commented on tests/benchmark.json
> +    "run": 0.957
Higher CPU performance and longer run time - should we be worried?

2024-10-30 16:45 UTC, daniel-klein commented on starsim/networks.py
> +    def remove_uids(self, uids):
If using `MixingPool` as an intervention in a Sim, this code will not be called, right?

2024-10-30 16:46 UTC, daniel-klein requested changes
Some changes required for the `rate_prob`

2024-10-31 06:01 UTC, cliffckerr commented on tests/benchmark.json
> +    "run": 0.957
No, "run" is calculated as actual runtime multiplied by "cpu_performance" (i.e., your run probably took about 1 second). In other words, "run" should be consistent regardless of "cpu_performance". I don't know why for you, both were so much lower -- I think the "cpu_performance" calculation wasn't quite accurate.

2024-10-31 08:29 UTC, cliffckerr commented on starsim/demographics.py
> +        self.n_pregnancies = len(conceive_uids)
Ah ok, that seems like it might be an anti-pattern, but will revert for now!

2024-10-31 08:49 UTC, cliffckerr commented on starsim/distributions.py
> +    integer = sc.sha(string, asint=True) # Hash the string to an integer
Updated. 10M is intended to be a compromise between human readability and absurdly low probability of collisions. But actually the probability isn't as low as I thought, so I upped this to 1 billion (which is now an average of roughly one collision per million sims -- certainly not enough to affect results!).

2024-10-31 08:50 UTC, cliffckerr commented on starsim/networks.py
> +            contact_matrix = np.array([[2.4, 0.49], [0.91, 0.16]]), # TODO: document where these came from
I've removed the defaults and added them to a docstring example instead.

2024-10-31 08:51 UTC, cliffckerr commented on starsim/networks.py
> +            src = None,
Why not assume that `src=None` is all agents?

2024-10-31 08:52 UTC, cliffckerr commented on starsim/networks.py
> +    def remove_uids(self, uids):
Correct, which will lead to bugs in the corner case of running with `src` or `dst` being explicit UIDs with demographics turned on.

2024-10-31 08:52 UTC, cliffckerr commented on starsim/networks.py
> +        return n_new_cases
Added

2024-10-31 08:52 UTC, cliffckerr commented on starsim/timepars.py
> +class rate_prob(TimePar):
Well spotted, fixed!

2024-10-31 09:11 UTC, closed without merging